services:
  - type: web
    name: design-audit-app
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false
      - key: QSTASH_TOKEN
        sync: false
      - key: QSTASH_URL
        sync: false
      - key: QSTASH_CURRENT_SIGNING_KEY
        sync: false
      - key: QSTASH_NEXT_SIGNING_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
